import 'server-only';
import { headers } from 'next/headers';
import { SITE_URL } from '@/lib/site';

/**
 * Shared email HTML — the shell every Loving Charmz email renders inside.
 *
 * Built for hostile clients: table-based layout, inline styles only, no web
 * fonts in text (webmail strips `<link>` tags and style blocks, so live text
 * can never carry the brand script — "Charmz" ships as a pre-rendered PNG
 * wordmark instead, generated by `npm run icons` from the site's font).
 */

/**
 * Escapes user/provider-supplied text before it is interpolated into email
 * HTML. Email clients render HTML with scripts disabled, but unescaped angle
 * brackets still let a crafted product name or address rewrite the layout,
 * forge links, or hide content — so everything shopper-controlled goes
 * through this.
 */
export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Absolute site origin for email links.
 *
 * Emails are read in a mail client, not on our origin, so request-derived
 * hosts (preview URLs, `localhost:3000`) are wrong more often than right;
 * fall back to the canonical production domain (`SITE_URL`) when
 * `NEXT_PUBLIC_SITE_URL` is unset and no request is in scope.
 */
export async function siteOrigin(): Promise<string> {
  const configured = (process.env.NEXT_PUBLIC_SITE_URL ?? '').trim().replace(/\/+$/, '');
  if (configured) return configured;

  // headers() throws outside a request scope (scripts, some webhook runtimes);
  // that is fine, we just fall back to the production domain.
  try {
    const headerList = await headers();
    const host =
      (headerList.get('x-forwarded-host') ?? headerList.get('host') ?? '').trim();
    if (host) {
      const proto =
        headerList.get('x-forwarded-proto') ??
        (host.startsWith('localhost') || host.startsWith('127.0.0.1') ? 'http' : 'https');
      return `${proto}://${host}`;
    }
  } catch {
    // Not in a request scope — fall through to the production default.
  }
  return SITE_URL;
}

/* ------------------------------------------------------------------ */
/*  Shell                                                              */
/* ------------------------------------------------------------------ */

export async function shell(content: string): Promise<string> {
  const site = await siteOrigin();
  // Deep-linking signed-in shoppers to My Orders beats the homepage; guests
  // just see the sign-in wall first.
  const accountHref = `${site}/account/orders`;
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#faf8f5;font-family:Georgia,'Times New Roman',serif;color:#1a1a1a;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#faf8f5;padding:32px 16px;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:8px;overflow:hidden;">

  <!-- Header: logo mark + wordmark, both linking to the shop -->
  <tr><td style="background:#2d1b4e;padding:26px 32px 24px;text-align:center;">
    <a href="${site}/shop" style="text-decoration:none;"><img src="${site}/email/logo.png" width="72" height="72" alt="Loving Charmz logo" style="display:block;margin:0 auto 10px;border:0;"></a>
    <a href="${site}/shop" style="text-decoration:none;">
      <span style="display:block;margin:0 0 2px;font-size:11px;color:#e8d5f5;letter-spacing:5px;text-transform:uppercase;">Loving</span>
      <img src="${site}/email/wordmark.png" width="118" height="55" alt="Charmz" style="display:block;margin:0 auto;border:0;">
    </a>
  </td></tr>

  <!-- Body -->
  <tr><td style="padding:32px;">
${content}
  </td></tr>

  <!-- Footer: links + studio note -->
  <tr><td style="background:#f5f0f7;padding:24px 32px;text-align:center;font-size:12px;color:#6b5b7b;">
    <p style="margin:0 0 8px;">Loving Charmz &mdash; Symbolic keepsake jewelry</p>
    <p style="margin:0 0 8px;">
      <a href="${site}" style="color:#6b5b7b;">lovingcharmz.com</a>
      &nbsp;&middot;&nbsp;
      <a href="${site}/shop" style="color:#6b5b7b;">Shop</a>
      &nbsp;&middot;&nbsp;
      <a href="${accountHref}" style="color:#6b5b7b;">My Orders</a>
      &nbsp;&middot;&nbsp;
      <a href="${site}/faq" style="color:#6b5b7b;">FAQ</a>
      &nbsp;&middot;&nbsp;
      <a href="mailto:hello@lovingcharmz.com" style="color:#6b5b7b;">Contact</a>
    </p>
    <p style="margin:0;color:#9b8fae;">Sent with care from the Loving Charmz studio.</p>
  </td></tr>

</table>
</td></tr>
</table>
</body>
</html>`;
}

/* ------------------------------------------------------------------ */
/*  Broadcasts (mailing-list emails from the admin composer)           */
/* ------------------------------------------------------------------ */

/** Marker the composer preview swaps for a live unsubscribe demo link. */
export const BROADCAST_UNSUBSCRIBE_TOKEN = '%%UNSUBSCRIBE_URL%%';

/**
 * Renders the complete, branded HTML for a broadcast email.
 *
 * The admin writes body-only HTML (a heading, a paragraph, a button); this
 * wraps it in the same shell as every other email — logo header, Caveat
 * wordmark, footer — and appends the mailing-list footer with the
 * per-recipient unsubscribe link (replaces any token the admin included).
 *
 * The body is interpolated **verbatim** — it is admin-authored trusted
 * content, not shopper input.
 */
export async function renderBroadcastHtml(params: {
  siteUrl: string;
  bodyHtml: string;
  unsubscribeUrl: string;
}): Promise<string> {
  const site = params.siteUrl.replace(/\/+$/, '');
  const unsub = params.unsubscribeUrl.replace(/\/+$/, '');

  // An admin may paste the token from the composer's hint; if they didn't,
  // append the unsubscribe block so CAN-SPAM / Gmail-Yahoo bulk rules hold
  // for every send regardless.
  const body = params.bodyHtml.includes(BROADCAST_UNSUBSCRIBE_TOKEN)
    ? params.bodyHtml.split(BROADCAST_UNSUBSCRIBE_TOKEN).join(`${unsub}?email=%%RECIPIENT_EMAIL%%`)
    : params.bodyHtml;

  return shell(`
    ${body}

    <div style="margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#999;text-align:center;">
      You're receiving this because you signed up at <a href="${site}" style="color:#999;">lovingcharmz.com</a>.
      <br><a href="${unsub}?email=%%RECIPIENT_EMAIL%%" style="color:#999;">Unsubscribe</a>
    </div>
  `);
}
